src/Deerpark/Models/GetInTouch.cs
using Deerpark.Models.Validators;
using FluentValidation.Attributes;

namespace Deerpark.Models
{
    [Validator(typeof(GetInTouchValidator))]
    public class GetInTouch
    {
        public string Subject { get; set; }
        public string From { get; set; }
        public string Content { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
    }
}

src/Deerpark/Models/Service.cs
namespace Deerpark.Models
{
    public class Service
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

src/Deerpark/Models/Validators/GetInTouchValidator.cs
using FluentValidation;

namespace Deerpark.Models.Validators
{
    public class GetInTouchValidator : AbstractValidator<GetInTouch>
    {
        public GetInTouchValidator()
        {
            RuleFor(x => x.Content).NotEmpty().WithMessage("Please enter a message")
                .Length(1, 2000).WithMessage("Please enter a shorter message (2000 characters)");

            RuleFor(x => x.SenderEmail).NotEmpty().WithMessage("Please enter your email address")
                .EmailAddress().WithMessage("Please enter a valid email address");

            RuleFor(x => x.Subject).NotEmpty().WithMessage("Please enter a subject")
                .Length(1, 200).WithMessage("Please enter a shorter subject (200 characters)");

            RuleFor(x => x.SenderName).NotEmpty().WithMessage("Please enter your name")
                .Length(0, 200).WithMessage("Please enter a shorter name (200 characters");
        }
    }
}

src/Deerpark/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Deerpark.Models;

namespace Deerpark.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        [Route("get-in-touch")]
        public ActionResult GetInTouch()
        {
            return View();
        }

        [Route("get-in-touch"), HttpPost, ValidateAntiForgeryToken]
        public ActionResult GetInTouch(GetInTouch getInTouch)
        {
            if (ModelState.IsValid)
            {
                var toAddress = ConfigurationManager.AppSettings["ContactFormToAddress"];

                using (var emailClient = new SmtpClient())
                {
                    var message = new MailMessage
                    {
                        To = { new MailAddress(toAddress)},
                        From = new MailAddress("website@deerparkengineering.com"),
                        Subject = getInTouch.Subject,
                        Body = BuildEmailBody(getInTouch)
                    };

                    emailClient.Send(message);
                }

                ModelState.Clear();
                ViewBag.Success = true;
                ViewBag.Message = "Thank you, your message has been sent";
                return View(new GetInTouch());
            }

            ViewBag.Success = false;
            ViewBag.Message = "Sorry, your message could not be sent.  Please try again or phone us on XXXXXXXXXXX";
            return View(getInTouch);
        }

        private string BuildEmailBody(GetInTouch getInTouch)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("You have received a message from:");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine(string.Format("Name: {0}", getInTouch.SenderName));
            stringBuilder.AppendLine(string.Format("Email Address: {0}", getInTouch.SenderEmail));
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("Message:");
            stringBuilder.AppendLine(getInTouch.Content);

            return stringBuilder.ToString();
        }

        [Route("about-us")]
        public ActionResult About()
        {
            return View();
        }

        [Route("sustainable-corporate-and-social-responsibility")]
        public ActionResult SocialAndCorporate()
        {
            return View();
        }
    }
}

src/Deerpark/Controllers/ServicesController.cs
using System.Web.Mvc;
using Deerpark.Models;

namespace Deerpark.Controllers
{
    [RoutePrefix("services")]
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Route("control-panels")]
        public ActionResult ControlPanels()
        {
            var model = new Service
            {
                Name = "Control Panels"
            };

            return View("ControlPanels", model);
        }

        [Route("electrical-installation")]
        public ActionResult ElectricalInstallation()
        {
            var model = new Service
            {
                Name = "Electrical Installation & Testing"
            };

            return View("ElectricalInstallation", model);
        }

        [Route("wind")]
        public ActionResult Wind()
        {
            var model = new Service
            {
                Name = "Wind"            
            };

            return View("Wind", model);
        }

        [Route("mechanical-services")]
        public ActionResult MechanicalServices()
        {
            var model = new Service
            {
                Name = "Mechanical Services"
            };

            return View("MechanicalServices", model);
        }

        [Route("pumping-and-screening-equipment")]
        public ActionResult PumpingAndScreening()
        {
            var model = new Service
            {
                Name = "Pumping & Screening Equipment"
            };

            return View("PumpingAndScreening", model);
        }
    }
}

src/Deerpark/Views/Home/About.cshtml
<h3>About</h3>

<div class="page-content">
    <p>
        Deerpark Engineering was established in 2011 to meet industry requirements for smoother and less complex project implementation. Deerpark Engineering is able to offer the full range of installation, cabling and project management capabilities, from minor works right through to larger projects.
        We have successfully managed a whole range of projects, and can take a job from concept through design, installation and testing to completion.
    </p>

    <p>
        By taking a multi-disciplined approach to systems design, we are best placed to facilitate every aspect of an installation.
        All of our installation work is installed to the highest standard and we can work to any particular specifications which may be required.
        All of our workforce are fully qualified and hold CSR cards, water hygiene cards, EUSR cards have had confined space training and are trained in first aid at work.
    </p>

    <p>
        We have extensive experience in working with not only the water utility on any given project, but also with multiple control equipment vendors, contractors and consultants.
        We can bring our project management services to you on an interim, short-term or long-term basis, with our focus on delivering on your requirements in every department of the project to help ensure repeat business.
    </p>

    <p>
        Our services encompass:
    </p>

    <ul class="default-list">
        <li>Project management</li>
        <li>Delivery services</li>
        <li>Electrical installation and cabling</li>
        <li>Instrumentation</li>
        <li>Commissioning and testing</li>
    </ul>

    <p>
        Our specialist project management personnel will work with you to see a project through.
    </p>
</div>

src/Deerpark/Views/Home/GetInTouch.cshtml
@model Deerpark.Models.GetInTouch

<div id="location" class="row">
    <h3>Where We Are</h3>
    <div id="map-canvas"></div>
</div>

<div id="email" class="row">
    <div class="section group">
        <div class="col col_1">

            <h3>Contact Us</h3>

            @if (!string.IsNullOrEmpty((string)ViewBag.Message))
            {
                var cssClass = (bool)ViewBag.Success ? "success" : "error";

                <div class="notification @cssClass">
                    <p>@ViewBag.Message</p>
                </div>
            }

            @using (Html.BeginForm("GetInTouch", "Home"))
            {
                @Html.AntiForgeryToken()

                <div class="field-group">
                    <label for="SenderName">Contact Name</label>

                    @Html.TextBoxFor(x => x.SenderName, new { placeholder = "Contact Name" })
                    @Html.ValidationMessageFor(x => x.SenderName)

                </div>

                <div class="field-group">
                    <label for="SenderEmail">Your email address</label>

                    @Html.TextBoxFor(x => x.SenderEmail, new { placeholder = "Email Address" })
                    @Html.ValidationMessageFor(x => x.SenderEmail)

                </div>

                <div class="field-group">
                    <label for="Subject">Reference</label>
                    @Html.TextBoxFor(x => x.Subject, new { placeholder = "Subject" })
                    @Html.ValidationMessageFor(x => x.Subject)
                </div>

                <div class="field-group">
                    <label for="Content">Message</label>
                    @Html.TextAreaFor(x => x.Content, new { placeholder = "Message" })
                    @Html.ValidationMessageFor(x => x.Content)
                </div>
                <div class="field-group">
                    <input class="button submit-btn" type="submit" value="Send Message">
                </div>
            }
        </div>
        <div class="col col_1">
            <div id="contact-details">
                <div class="heading-text">
                    <p>
                        Please feel free to contact us using the form on the left.
                        Alternatively you can find us using the information below.
                    </p>
                </div>
                
                <div class="contact-details">
                    <p><i class="contact-icon fa fa-location-arrow"></i>47 Deerpark Road, Glenarm, Ballymena BT44 0DW</p>
                    <p><i class="contact-icon fa fa-phone"></i>02828841864</p>
                    <p><i class="contact-icon fa fa-envelope-o"></i><a href="mailto:info@deerparkengineering.com">info@deerparkengineering.com</a></p>
                </div>
            </div>
        </div>
    </div>


</div>

@section scripts{
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyDvR-EHhzY2QHR9yTkfHc3J68uPPRJnkmw"></script>
    <script src="~/Scripts/deerpark.map.js"></script>
}

src/Deerpark/Views/Home/Index.cshtml
<div id="slider" class="barousel">
    <div class="barousel_image">
        <img src="~/Content/Images/Deerpark-Windmill.jpg" alt="Wind Turbine Installed at Glens of Antrim" title="Endurance E3120 Wind Turbine" class="default" />
        <img src="~/Content/Images/Deerpak-Control-Panel.jpg" alt="MCC installed for the control of screening equipment" title="Downpatrick WWTW" />
        <img src="~/Content/Images/Deerpark-Pumping-Screening.jpg" alt="Pumping station" title="Cairnryan Link Span Scotland Pumping Station" />
        <img src="~/Content/Images/Deerpark-Electrical-Installation.jpg" alt="Multi-core installation to wind turbines" title="Molly Mountain Wind Farm" />
    </div>
    <div class="barousel_content">
        <div class="default">
            <h3>Endurance E3120 Wind Turbine</h3>
            <p>
                A single wind turbine installed in the Glens of Antrim.
            </p>
        </div>
        <div>
            <h3>Downpatrick WWTW</h3>
            <p>
                MCC installed for the control of new screening equipment.
            </p>
        </div>
        <div>
            <h3>Cairnryan Link Span Scotland</h3>
            <p>
                Pumping Station to control the level of the Link Span.
            </p>
        </div>
        <div>
            <h3>Molly Mountain Wind Farm</h3>
            <p>
                Multi-core installation to wind turbines.
            </p>
        </div>
    </div>
    <div class="barousel_nav">
    </div>
</div>

<div id="service-boxes">
    <div class="box">
        <div class="title">Control Panels</div>
        <div class="service-img">
            <a href="@Url.Action("ControlPanels", "Services")" title="Find out more">
                <img src="~/Content/Images/Service-Boxes/Service-Control-Panel.jpg" alt="Control Panel Installations" title="Control Panels" />
            </a>
        </div>
    </div>
    <div class="box">
        <div class="title">Electrical Installation & Testing</div>
        <div class="service-img">
            <a href="@Url.Action("ElectricalInstallation", "Services")" title="Find out more">
                <img src="~/Content/Images/Service-Boxes/Service-Electrical-Installation.jpg" alt="Electrical Installation" title="Electrical Installation" />
            </a>
        </div>
    </div>
    <div class="box">
        <div class="title">Wind</div>
        <div class="service-img">
            <a href="@Url.Action("Wind", "Services")" title="Find out more">
                <img src="~/Content/Images/Service-Boxes/Service-Wind.jpg" alt="Wind Services and Installation" title="Wind" />
            </a>
        </div>
    </div>
    <div class="box">
        <div class="title">Mechanical Services</div>
        <div class="service-img">
            <a href="@Url.Action("MechanicalServices", "Services")" title="Find out more">
                <img src="~/Content/Images/Service-Boxes/Service-Mechanical-Services.jpg" alt="Mechanical Services" title="Mechanical Services" />
            </a>
        </div>
    </div>
    <div class="box">
        <div class="title">Pumping & Screening</div>
        <div class="service-img">
            <a href="@Url.Action("PumpingAndScreening", "Services")" title="Find out more">
                <img src="~/Content/Images/Service-Boxes/Service-Pumping-Screening.jpg" alt="Pumping and Screening Installation" title="Pumping and Screening" />
            </a>
        </div>
    </div>
    <div class="box">
        <div class="title">Corporate and Social Responsibility</div>
        <div class="service-img">
            <a href="@Url.Action("SocialAndCorporate", "Home")" title="Find out more">
                <img src="~/Content/Images/Service-Boxes/Social-And-Corporate.jpg" alt="Sustainable Corporate and Social Responsibility" title="Sustainable Corporate and Social Responsibility" />
            </a>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.barousel.min.js"></script>
    <script src="~/Scripts/index.js"></script>
}

src/Deerpark/Views/Home/SocialAndCorporate.cshtml
<h3>Sustainable Corporate and Social Responsibility</h3>

<div class="page-content">
    <p>In Deerpark Engineering, we recognise Sustainable Development as an integral part of our core organisational strategy. For us, this concept translates into a genuine commitment to meet the needs of society while operating within the limits of environment. Sustainable Development in Deerpark Engineering targets long term growth and profit from a position of social co-operation and value creation. We embrace the broad expectations of society as a whole.</p>
    <p>We are committed to operating in an ethical and socially responsible manner which contributes to Sustainable Development. This standard applies to all divisions within our Company.</p>
    <p>Deerpark Engineering is committed to supporting the vision for Corporate Social responsibility by:</p>

    <ul class='default-list'>
        <li>Dealing openly and honestly with clients and suppliers</li>
        <li>Commitment to the well-being and training of employees and working in a safe environment</li>
        <li>Supporting the local community</li>
        <li>Reducing our effect on the environment.</li>
    </ul>

    <p>We will ensure that we deal responsibly, openly and fairly with our clients and potential clients by:</p>

    <ul class='default-list'>
        <li>Being open and honest about our services</li>
        <li>Acknowledging problems and dealing with them</li>
        <li>Benchmarking and evaluating what we do in order to constantly improve our performance</li>
    </ul>

    <p>We will deal responsibly, openly and fairly with suppliers and ensure that we use local suppliers wherever practicable.</p>
    <p>We are committed to the wellbeing and training of our staff and to providing them with a safe working environment.</p>
    <p>We support the local community by:</p>

    <ul class='default-list'>
        <li>Sponsoring local community groups such as Youth Clubs and the local Athletic Running Club of which a few of the workforce are members</li>
        <li>We help local community by volunteering our time to local projects</li>
    </ul>

    <p>We are committed to reducing our effect on the environment by:</p>

    <ul class='default-list'>
        <li>Monitoring and aiming to reduce energy, water and paper and cardboard usage</li>
        <li>Maximising reuse and recycling of materials</li>
        <li>Managing and disposal of all waste in a responsible manner</li>
        <li>Any old electrical equipment removed from site is disposed of to a registered WEEE Merchant</li>
        <li>All timber is recycled for chipping which goes to the bedding of Farm Animals</li>
    </ul>
</div>

src/Deerpark/Views/Services/ControlPanels.cshtml
@model Deerpark.Models.Service
           
<div id="services" class="row">

    <div id="sidebar">
        @Html.Partial("_ServiceNav")
    </div>

    <div id="content">
        <h3>@Model.Name</h3>

        <p>When you enter periods of change, looking to update and improve critical systems and infrastructure, Deerpark Engineering is here to help you reap the benefits of advanced control and automation technology.</p>
        <p>The pressure on Utility Sector to perform is immense, but Deerpark Engineering combines an unparalleled understanding of the requirements of the sector with an unrivalled expertise in systems design and implementation to help you rise to the challenges.</p>
        <p>Our capabilities span the design, manufacture, installation, test, commissioning and lifecycle support of electrical systems. We tightly integrate all the key disciplines of mechanical, electrical, instrumentation and systems integration to ensure that we have all the skills we need under one roof to develop control and automation systems that offer:</p>

        <ul class='default-list'>
            <li>Right first time design</li>
            <li>Reduced capital costs</li>
            <li>Consistently high quality</li>
            <li>Guaranteed safety compliance</li>
            <li>Improved reliability</li>
            <li>Reduced maintenance costs</li>
            <li>Guaranteed on-time delivery</li>
        </ul>

        <p>We have a huge depth of capabilities and in-house resources. With our specialisation in the water and waste water industries and our proven track record in delivering innovative systems that meet and exceed your expectations and requirements, Deerpark Engineering is your ideal business partner for managing change.</p>
    </div>
</div>

src/Deerpark/Views/Services/ElectricalInstallation.cshtml
@model Deerpark.Models.Service

<div id="services" class="row">

    <div id="sidebar">
        @Html.Partial("_ServiceNav")
    </div>

    <div id="content">
        <h3>@Model.Name</h3>

        <p>For installation, Deerpark Engineering is an NICEIC approved contractor, with extensive experience in both new systems installation and refurbishment of existing equipment. Our project experience in delivering site services to the Utilities and Water industry encompasses everything from MCC installation and cabling, to the installation of site level controls, to the rewiring of control systems for existing plant, to re-cabling and updating a whole water or sewage treatment works.</p>
        <p>Our resources include commissioning and testing engineers throughout Northern Ireland.</p>
        <p>We are:</p>

        <ul class='default-list'>
            <li>Experts in providing a complete design package</li>
            <li>NICEIC approved</li>
            <li>Specialists in refurbishment</li>
            <li>Able to provide periodic testing</li>
            <li>Able to provide full documentation and manuals</li>
        </ul>

        <p>An important differentiator for Deerpark Engineering is our high level of post-project support and system maintenance. We are able to provide a range of tailored services, from a 'man in a van' to total care packages, all at highly competitive rates.</p>
    </div>
</div>

src/Deerpark/Views/Services/Index.cshtml
<div id="services" class="row">
    
    <div id="sidebar">
        @Html.Partial("_ServiceNav")
    </div>

    <div id="content">
        <h3>Our Services</h3>
        <p>
            Laoreet ac, aliquam sit amet justo nunc tempor, metus vel placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis
            scelerisque eu ac ante fusce non varius purus aenean nec magna felis fusce vestibulum.
        </p>
    </div>
</div>

src/Deerpark/Views/Services/MechanicalServices.cshtml
@model Deerpark.Models.Service

<div id="services" class="row">

    <div id="sidebar">
        @Html.Partial("_ServiceNav")
    </div>

    <div id="content">
        <h3>@Model.Name</h3>

        <p>With the rapid changes in the Utility sector and the need for quick installations to minimise downtime, Deerpark Engineering has the knowledge and skill to install the following:</p>

        <ul class='default-list'>
            <li>Stainless Steel</li>
            <li>HPPE fusion welded</li>
            <li>MDPE</li>
            <li>Ductile Iron</li>
            <li>U-PVC</li>
            <li>ABS</li>
            <li>BSP Black Iron</li>
        </ul>
    </div>
</div>

src/Deerpark/Views/Services/PumpingAndScreening.cshtml
@model Deerpark.Models.Service
           
<div id="services" class="row">

    <div id="sidebar">
        @Html.Partial("_ServiceNav")
    </div>

    <div id="content">
        <h3>@Model.Name</h3>

        <p>From a single pump in a borehole to a multiple pumping system on a Waste Water Treatment Works Deerpark Engineering can offer solutions from the simple to the complex, we offer design, supply and commissioning of Waste Water Pumping Stations with the following:</p>

        <ul class='default-list'>
            <li>GRP Kiosks</li>
            <li>Motor Control Centres</li>
            <li>Submersible and dry well submersible pumps</li>
            <li>Pipework</li>
            <li>Electrical Installation</li>
            <li>Overflow screens to comply with local authorities </li>
            <li>Telemetry</li>
            <li>Testing</li>
            <li>Commissioning</li>
        </ul>
    </div>
</div>

src/Deerpark/Views/Services/Service.cshtml
@model Deerpark.Models.Service

<div id="service" class="row">

    <div id="sidebar">
        @Html.Partial("_ServiceNav")
    </div>

    <div id="content">
        <h3>@Model.Name</h3>
        
        @Html.Raw(Model.Description)
        
    </div>
    

</div>

src/Deerpark/Views/Services/Wind.cshtml
@model Deerpark.Models.Service

<div id="services" class="row">

    <div id="sidebar">
        @Html.Partial("_ServiceNav")
    </div>

    <div id="content">
        <h3>@Model.Name</h3>

        <p>With our fossil fuels in rapid decline, wind has been a proven energy in the recent decades, with more and more people realising the benefits of this natural and sustainable energy Deerpark Engineering has been involved from the installation of a single Turbine to the complete electrical installation of a Wind Farm.</p>
    </div>
</div>

src/Deerpark/Views/Services/_ServiceNav.cshtml
@using Deerpark.Extensions
<nav>
    <ul>
        <li @Html.CssClass("selected", ViewContext.IsSpecificAction("ControlPanels", "Services"))><a href="@Url.Action("ControlPanels", "Services")">Control Panels</a></li>
        <li @Html.CssClass("selected", ViewContext.IsSpecificAction("ElectricalInstallation", "Services"))><a href="@Url.Action("ElectricalInstallation", "Services")">Electrical Installation & Testing</a></li>
        <li @Html.CssClass("selected", ViewContext.IsSpecificAction("Wind", "Services"))><a href="@Url.Action("Wind", "Services")">Wind</a></li>
        <li @Html.CssClass("selected", ViewContext.IsSpecificAction("MechanicalServices", "Services"))><a href="@Url.Action("MechanicalServices", "Services")">Mechanical Services</a></li>
        <li @Html.CssClass("selected", ViewContext.IsSpecificAction("PumpingAndScreening", "Services"))><a href="@Url.Action("PumpingAndScreening", "Services")">Pumping & Screening Equipment</a></li>        
        
    </ul>
</nav>

src/Deerpark/Views/Shared/_Layout.cshtml
@using Deerpark.Extensions
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="control panels, electrical installtion, pumping stations, wind, instrumentation, project management, deerpark, engineering, northern ireland">
    <meta name="description" content="Mechanical engineering across Northern Ireland and the UK.">
    <title>Deerpark Engineering</title>
    <link href="~/Content/Styles/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel='shortcut icon' href='~/Content/Images/favicon.ico' type='image/x-icon' />
</head>
<body>
<div class="wrapper">
    <header>
        <div class="bar">
            <div class="container">
                <div id="contact-summary" class="right">
                    <span class="pad-right-large"><a href="mailto:info@deerparkengineering.com">info@deerparkengineering.com</a></span>
                    <span>02828841864</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="logo">
                <a href="@Url.Action("Index", "Home")">
                    <img src="../../Content/Images/logo.png" alt=""/>
                </a>
            </div>
            <nav>
                <ul>
                    <li><a @Html.CssClass("selected", ViewContext.IsSpecificAction("Index", "Home")) href="@Url.Action("Index", "Home")">Home</a></li>
                    <li><a @Html.CssClass("selected", ViewContext.IsSpecificAction("About", "Home")) href="@Url.Action("About", "Home")">About Us</a></li>
                    <li><a @Html.CssClass("selected", ViewContext.IsSpecificController("Services")) href="@Url.Action("ControlPanels", "Services")">Services</a></li>
                    <li><a @Html.CssClass("selected", ViewContext.IsSpecificAction("GetInTouch", "Home")) href="@Url.Action("GetInTouch", "Home")">Contact Us</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="container">
        @RenderBody()
        <div class="push"></div>
    </div>
</div>

<footer>
    <div id="footer-content"class="container">
        <span>Copyright © 2015 Deerpark Engineering</span>
        
        <div id="accreditations" class="right" title="Our Accreditations">
            <img src="~/Content/Images/Accreditations/ConstructionLine.png" alt="Construction Line Certification" title="Construction Line"/>
            <img src="~/Content/Images/Accreditations/ISO9001.png" alt="ISO9001 Certification" title="ISO9001" />
            <img src="~/Content/Images/Accreditations/NICEIC.png" alt="NICEIC Certification" title="NICEIC" />
            <img src="~/Content/Images/Accreditations/SafeTcert.png" alt="SafeTcert Certification" title="SafeTcert" />
        </div>

    </div>
</footer>


<script src="~/Scripts/jquery-2.1.3.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>